import { ChallengeCardModel } from './types';

export const INITIAL_CHALLENGES: ChallengeCardModel[] = [
  {
    id: 'ch-active-1',
    name: '30-Day Morning Core Routine',
    category: 'Fitness',
    status: 'ACTIVE',
    startAt: '2026-08-15',
    endAt: '2026-09-14',
    score: 84.6,
    rank: 4,
    memberCount: 28,
    completion: 92,
    consistency: 86,
    participation: 79,
    currentDay: 23,
    totalDays: 30,
    routineLocked: true,
    isCreator: false,
    joined: true,
    todayBlocks: [
      {
        id: 'tb-1',
        dayOfWeek: 4,
        startTime: '07:00',
        endTime: '07:35',
        title: 'High-Plank & Hollow Hold Progression',
        category: 'Strength',
        completed: false,
      },
      {
        id: 'tb-2',
        dayOfWeek: 4,
        startTime: '07:35',
        endTime: '07:50',
        title: 'Thoracic Mobility & Cool Down',
        category: 'Mobility',
        completed: false,
      },
    ],
    allWeeklyRoutine: [
      { id: 'm-1', dayOfWeek: 1, startTime: '07:00', endTime: '07:45', title: 'Dynamic Core Intervals', category: 'Strength', completed: true },
      { id: 't-1', dayOfWeek: 2, startTime: '07:00', endTime: '07:45', title: 'Oblique Stability Circuit', category: 'Strength', completed: true },
      { id: 'w-1', dayOfWeek: 3, startTime: '07:00', endTime: '07:30', title: 'Active Pelvic Mobility & Rest', category: 'Mobility', completed: true },
      { id: 'th-1', dayOfWeek: 4, startTime: '07:00', endTime: '07:35', title: 'High-Plank & Hollow Hold Progression', category: 'Strength', completed: false },
      { id: 'f-1', dayOfWeek: 5, startTime: '07:00', endTime: '07:45', title: 'Endurance Core Test', category: 'Strength', completed: false },
    ],
    leaderboard: [
      { id: 'usr-1', name: 'Elena Rostova', score: 96.2, rank: 1, completionRate: 100, consistencyRate: 98, participationRate: 92 },
      { id: 'usr-2', name: 'Marcus Chen', score: 91.8, rank: 2, completionRate: 95, consistencyRate: 92, participationRate: 90 },
      { id: 'usr-3', name: 'Devon Vance', score: 87.5, rank: 3, completionRate: 90, consistencyRate: 88, participationRate: 85 },
      { id: 'usr-curr', name: 'You (Alex Reed)', score: 84.6, rank: 4, isCurrentUser: true, completionRate: 92, consistencyRate: 86, participationRate: 79 },
      { id: 'usr-5', name: 'Sophia Larsson', score: 81.3, rank: 5, completionRate: 88, consistencyRate: 82, participationRate: 76 },
      { id: 'usr-6', name: 'Liam Davies', score: 77.0, rank: 6, completionRate: 84, consistencyRate: 78, participationRate: 71 },
      { id: 'usr-7', name: 'Amina Al-Mansoor', score: 74.2, rank: 7, completionRate: 80, consistencyRate: 75, participationRate: 69 },
    ],
  },
  {
    id: 'ch-upcoming-1',
    name: '10K Autumn Distance Builder',
    category: 'Running',
    status: 'UPCOMING',
    startAt: '2026-09-18',
    endAt: '2026-10-18',
    score: null,
    rank: null,
    memberCount: 14,
    completion: null,
    consistency: null,
    participation: null,
    currentDay: 0,
    totalDays: 30,
    routineLocked: false,
    isCreator: false,
    joined: false,
    todayBlocks: [],
    allWeeklyRoutine: [
      { id: 'r-tue', dayOfWeek: 2, startTime: '06:30', endTime: '07:15', title: 'Interval Aerobic Pace (5km)', category: 'Cardio' },
      { id: 'r-thu', dayOfWeek: 4, startTime: '06:30', endTime: '07:20', title: 'Tempo Threshold Run (6km)', category: 'Cardio' },
      { id: 'r-sat', dayOfWeek: 6, startTime: '08:00', endTime: '09:15', title: 'Long Continuous Base Run (9km)', category: 'Cardio' },
    ],
    leaderboard: [
      { id: 'u-1', name: 'Sarah Miller', score: 0, rank: 1, completionRate: 0, consistencyRate: 0, participationRate: 0 },
      { id: 'u-2', name: 'Jordan Hayes', score: 0, rank: 2, completionRate: 0, consistencyRate: 0, participationRate: 0 },
    ],
  },
  {
    id: 'ch-creator-unlocked-1',
    name: 'TypeScript Mastery: Type Gymnastics',
    category: 'Coding',
    status: 'UPCOMING',
    startAt: '2026-09-22',
    endAt: '2026-10-12',
    score: null,
    rank: null,
    memberCount: 0,
    completion: null,
    consistency: null,
    participation: null,
    currentDay: 0,
    totalDays: 20,
    routineLocked: false,
    isCreator: true,
    joined: true,
    todayBlocks: [],
    allWeeklyRoutine: [
      { id: 'ts-1', dayOfWeek: 1, startTime: '19:00', endTime: '20:00', title: 'Template Literal & Conditional Types', category: 'Practice' },
      { id: 'ts-2', dayOfWeek: 3, startTime: '19:00', endTime: '20:00', title: 'Recursive Tuples & Mapped Modifiers', category: 'Practice' },
      { id: 'ts-3', dayOfWeek: 5, startTime: '19:00', endTime: '20:15', title: 'Type-Level Arithmetic & AST Parsers', category: 'Practice' },
    ],
    leaderboard: [],
  },
  {
    id: 'ch-creator-locked-1',
    name: 'Mindful Breathing & Stillness Lab',
    category: 'Mindfulness',
    status: 'ACTIVE',
    startAt: '2026-09-01',
    endAt: '2026-09-30',
    score: 91.2,
    rank: 2,
    memberCount: 19,
    completion: 96,
    consistency: 94,
    participation: 88,
    currentDay: 10,
    totalDays: 30,
    routineLocked: true,
    isCreator: true,
    joined: true,
    todayBlocks: [
      {
        id: 'mb-1',
        dayOfWeek: 4,
        startTime: '06:15',
        endTime: '06:40',
        title: 'Box Breathing (4-4-4-4) & Diaphragmatic Rest',
        category: 'Mindfulness',
        completed: true,
      },
    ],
    allWeeklyRoutine: [
      { id: 'm-mon', dayOfWeek: 1, startTime: '06:15', endTime: '06:35', title: 'Sensory Grounding Protocol', category: 'Mindfulness', completed: true },
      { id: 'm-wed', dayOfWeek: 3, startTime: '06:15', endTime: '06:35', title: 'Coherent Breathing (5.5s Pace)', category: 'Mindfulness', completed: true },
      { id: 'm-fri', dayOfWeek: 5, startTime: '06:15', endTime: '06:40', title: 'Deep Vipassana Scan', category: 'Mindfulness', completed: false },
    ],
    leaderboard: [
      { id: 'usr-zen1', name: 'Maya Lin', score: 94.5, rank: 1, completionRate: 98, consistencyRate: 96, participationRate: 92 },
      { id: 'usr-curr', name: 'You (Alex Reed)', score: 91.2, rank: 2, isCurrentUser: true, completionRate: 96, consistencyRate: 94, participationRate: 88 },
      { id: 'usr-zen3', name: 'Kai Tanaka', score: 88.0, rank: 3, completionRate: 92, consistencyRate: 90, participationRate: 85 },
      { id: 'usr-zen4', name: 'Eva Morales', score: 83.4, rank: 4, completionRate: 89, consistencyRate: 84, participationRate: 80 },
    ],
  },
  {
    id: 'ch-finalized-1',
    name: 'Deep Hydration & Sleep Hygiene 21',
    category: 'Wellness',
    status: 'FINALIZED',
    startAt: '2026-08-01',
    endAt: '2026-08-21',
    score: 89.4,
    rank: 3,
    memberCount: 42,
    completion: 95,
    consistency: 90,
    participation: 85,
    currentDay: 21,
    totalDays: 21,
    routineLocked: true,
    isCreator: false,
    joined: true,
    todayBlocks: [],
    allWeeklyRoutine: [
      { id: 'h-1', dayOfWeek: 1, startTime: '21:30', endTime: '22:00', title: 'Screen Shutdown & Herbal Infusion', category: 'Wellness', completed: true },
      { id: 'h-3', dayOfWeek: 3, startTime: '21:30', endTime: '22:00', title: 'Screen Shutdown & Magnesium Protocol', category: 'Wellness', completed: true },
      { id: 'h-5', dayOfWeek: 5, startTime: '21:30', endTime: '22:00', title: 'Pre-Sleep Guided Decompression', category: 'Wellness', completed: true },
    ],
    leaderboard: [
      { id: 'fn-1', name: 'Chloe Dubois', score: 94.0, rank: 1, completionRate: 98, consistencyRate: 95, participationRate: 91 },
      { id: 'fn-2', name: 'Samira Patel', score: 91.8, rank: 2, completionRate: 96, consistencyRate: 93, participationRate: 89 },
      { id: 'usr-curr', name: 'You (Alex Reed)', score: 89.4, rank: 3, isCurrentUser: true, completionRate: 95, consistencyRate: 90, participationRate: 85 },
      { id: 'fn-4', name: 'Oliver King', score: 82.1, rank: 4, completionRate: 88, consistencyRate: 84, participationRate: 78 },
    ],
  },
  {
    id: 'ch-cancelled-1',
    name: 'Weekend Alpine Trail Trekking Prep',
    category: 'Outdoors',
    status: 'CANCELLED',
    startAt: '2026-08-10',
    endAt: '2026-09-10',
    score: null,
    rank: null,
    memberCount: 8,
    completion: null,
    consistency: null,
    participation: null,
    currentDay: 12,
    totalDays: 30,
    routineLocked: true,
    isCreator: false,
    joined: false,
    todayBlocks: [],
    allWeeklyRoutine: [
      { id: 'c-1', dayOfWeek: 6, startTime: '07:30', endTime: '11:00', title: 'Weighted Incline Ruck (12kg)', category: 'Outdoors' },
    ],
    leaderboard: [],
  },
];
