import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// The tones bundled under assets/sounds, generated by
/// tool/generate_alarm_sounds.py. `silent` still buzzes if vibration is on —
/// it only suppresses the audio.
enum AlarmSound {
  chime('Chime', 'sounds/chime.wav'),
  bell('Bell', 'sounds/bell.wav'),
  beep('Beep', 'sounds/beep.wav'),
  silent('Silent', null);

  const AlarmSound(this.label, this.asset);

  final String label;
  final String? asset;

  static AlarmSound fromName(String? name) =>
      values.firstWhere((s) => s.name == name, orElse: () => AlarmSound.chime);
}

/// Alarm settings for the focus timer, kept on the device rather than in the
/// synced document: which tone plays belongs to the phone you are sitting next
/// to, and the web app has no concept of it.
class AlarmProvider extends ChangeNotifier {
  static const _kEnabled = 'alarm.enabled';
  static const _kSound = 'alarm.sound';
  static const _kVibrate = 'alarm.vibrate';

  /// How long the alarm rings on its own before giving up.
  static const _ringFor = Duration(seconds: 30);
  static const _vibrateEvery = Duration(milliseconds: 1200);

  final AudioPlayer _player = AudioPlayer(playerId: 'ordo-alarm');

  bool _enabled = true;
  bool _vibrate = true;
  AlarmSound _sound = AlarmSound.chime;
  bool _ringing = false;
  Timer? _stopTimer;
  Timer? _buzzTimer;

  bool get enabled => _enabled;
  bool get vibrate => _vibrate;
  AlarmSound get sound => _sound;
  bool get ringing => _ringing;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _enabled = prefs.getBool(_kEnabled) ?? true;
    _vibrate = prefs.getBool(_kVibrate) ?? true;
    _sound = AlarmSound.fromName(prefs.getString(_kSound));
    notifyListeners();
  }

  Future<void> setEnabled(bool value) async {
    _enabled = value;
    notifyListeners();
    if (!value) await stop();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_kEnabled, value);
  }

  Future<void> setVibrate(bool value) async {
    _vibrate = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_kVibrate, value);
  }

  /// Picking a tone previews it, so the choice can be made by ear.
  Future<void> setSound(AlarmSound value) async {
    _sound = value;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_kSound, value.name);
    await preview(value);
  }

  Future<void> preview(AlarmSound value) async {
    await stop();
    if (value.asset == null) {
      if (_vibrate) HapticFeedback.mediumImpact();
      return;
    }
    try {
      await _player.setReleaseMode(ReleaseMode.stop);
      await _player.play(AssetSource(value.asset!));
    } catch (e) {
      debugPrint('[alarm] preview failed: $e');
    }
  }

  /// Rings until [stop] is called, or until [_ringFor] elapses.
  Future<void> fire() async {
    if (!_enabled) return;
    _ringing = true;
    notifyListeners();

    if (_vibrate) {
      HapticFeedback.heavyImpact();
      _buzzTimer = Timer.periodic(_vibrateEvery, (_) => HapticFeedback.heavyImpact());
    }
    _stopTimer = Timer(_ringFor, stop);

    final asset = _sound.asset;
    if (asset == null) return;
    try {
      await _player.setReleaseMode(ReleaseMode.loop);
      await _player.play(AssetSource(asset));
    } catch (e) {
      debugPrint('[alarm] play failed: $e');
    }
  }

  Future<void> stop() async {
    _stopTimer?.cancel();
    _buzzTimer?.cancel();
    _stopTimer = null;
    _buzzTimer = null;
    if (_ringing) {
      _ringing = false;
      notifyListeners();
    }
    try {
      await _player.stop();
    } catch (_) {
      // Nothing was playing.
    }
  }

  @override
  void dispose() {
    _stopTimer?.cancel();
    _buzzTimer?.cancel();
    _player.dispose();
    super.dispose();
  }
}
